format_version: 3
environments:
  testing:
    environment_variables:
      DEPLOYMENT-PASSWORD: "{{SECRET:[my_secret1][api-user-password]}}"
      DEPLOYMENT-USER: "{{SECRET:[my_secret1][api-user]}}"
    pipelines:
      - mypipe1
pipelines:
  mypipe1: 
    group: mygroup
    label_template: "${mygit[:8]}"
    lock_behavior: none
    materials:
      mygit:
        git: https://github.com/adityasood/gocd-yaml-config-example.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            csharp:
              tasks: # ordered list of tasks to execute in job csharp
               - exec:
                   command: /bin/bash
                   arguments:
                    - "-c"
                    - "curl -k 'https://localhost:8154/go/api/admin/security/auth_configs/9cad79b0-4d9e-4a62-829c-eb4d9488062f' -u $DEPLOYMENT-USER:$DEPLOYMENT-PASSWORD -H 'Accept: application/vnd.go.cd.v1+json'"
