format_version: 3
environments:
  testing:
    environment_variables:
      DEPLOYMENT: abcdef
    pipelines:
      - mypipe1
pipelines:
  mypipe1: 
    group: mygroup
    label_template: "${mygit[:8]}"
    lock_behavior: none
    materials:
      mygit:
        git: https://github.com/adityasood/gocd-yaml-config-example.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            csharp:
              tasks: # ordered list of tasks to execute in job csharp
               - script: "echo -e $DEPLOYMENT"
