pipelines:
  hello_world1:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/gocd-contrib/getting-started-repo
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - default_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        environment_variables:
          DEPLOYMENT: "testing"
          FOO: "bar"
        secure_variables:
          MY_PASSWORD: "l4uWwU7WMV4="
        approval:
          type: success
        jobs:
          default_job:
            timeout: 0
            elastic_profile_id:
            tasks:
            - exec:
                arguments:
                - Hello World
                command: echo
                run_if: passed
