format_version: 3
pipelines:
  hello_world1:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/gocd-contrib/getting-started-repo
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - default_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          default_job:
            timeout: 0
            elastic_profile_id:
            artifacts:
            - external:
                id: hello-world-job
                store_id: docker-artifact
                configuration:
                  options:
                    BuildFile: ''
                    Tag: v0.0.2
                    Image: adityasood/test_image
            tasks:
            - exec:
                arguments:
                - -c
                - docker images;
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - Hello World
                command: echo
                run_if: passed
